// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9y6MHAAcDUHaP3w75klJOA_xrB4sIbQ',
    appId: '1:157714433125:web:9ea0fa2f92265320e5728c',
    messagingSenderId: '157714433125',
    projectId: 'storyapp-3de04',
    authDomain: 'storyapp-3de04.firebaseapp.com',
    storageBucket: 'storyapp-3de04.appspot.com',
    measurementId: 'G-2J7Y0RL24N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByAJswyS4kXYfK1MqkyEufgScb1rqC6yQ',
    appId: '1:157714433125:android:cb40db44bdbb026ae5728c',
    messagingSenderId: '157714433125',
    projectId: 'storyapp-3de04',
    storageBucket: 'storyapp-3de04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC2e7jGa8frVFJ2_gSf4bKsY-BxMWVvGw',
    appId: '1:157714433125:ios:b0bd53e458b73a8fe5728c',
    messagingSenderId: '157714433125',
    projectId: 'storyapp-3de04',
    storageBucket: 'storyapp-3de04.appspot.com',
    iosBundleId: 'com.story.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC2e7jGa8frVFJ2_gSf4bKsY-BxMWVvGw',
    appId: '1:157714433125:ios:b0bd53e458b73a8fe5728c',
    messagingSenderId: '157714433125',
    projectId: 'storyapp-3de04',
    storageBucket: 'storyapp-3de04.appspot.com',
    iosBundleId: 'com.story.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS9y6MHAAcDUHaP3w75klJOA_xrB4sIbQ',
    appId: '1:157714433125:web:3cd93ed30cf7df51e5728c',
    messagingSenderId: '157714433125',
    projectId: 'storyapp-3de04',
    authDomain: 'storyapp-3de04.firebaseapp.com',
    storageBucket: 'storyapp-3de04.appspot.com',
    measurementId: 'G-LSG1S075C2',
  );
}
